"""
<<<<<<< HEAD
tools/file_saver.py
--------------------
Output & File Saver Tool for the Research Agent.
Saves research reports as Markdown (.md) files into the outputs/ folder.
Also supports plain text (.txt) saving and listing saved reports.

Owner   : Member 3
Branch  : feature/file-saver-tool
API Key : None required
=======
tools/file_saver.py — Member 3 owns this file
AI Agent Project | Phase 1

Provides save_report() — called by research_agent.py to save the final report.
Saves reports to the outputs/ folder as markdown files.
>>>>>>> a1f9972 (reseacrh_agent connected with the file_saver.py)
"""

import os
import re
from datetime import datetime
<<<<<<< HEAD
from pathlib import Path
from typing import Optional

# ── Resolve paths relative to the project root ───────────────────────────────
# This works correctly regardless of where Python is run from.
PROJECT_ROOT  = Path(__file__).resolve().parent.parent
OUTPUTS_DIR   = PROJECT_ROOT / "outputs"


# ─────────────────────────────────────────────────────────────────────────────
# Internal helpers
# ─────────────────────────────────────────────────────────────────────────────

def _ensure_outputs_dir() -> Path:
    """
    Make sure the outputs/ directory exists.
    Creates it silently if it doesn't.

    Returns:
        Path object pointing to outputs/
    """
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    return OUTPUTS_DIR


def _slugify(text: str) -> str:
    """
    Convert a topic string into a safe, lowercase filename slug.

    Examples:
        "LangChain Agents"  →  "langchain_agents"
        "What is GPT-4?"    →  "what_is_gpt-4"
    """
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)       # remove special chars except - _
    text = re.sub(r"[\s]+", "_", text)          # spaces → underscores
    text = re.sub(r"_+", "_", text)             # collapse multiple underscores
    return text[:60]                             # cap length at 60 chars


def _build_markdown(topic: str, content: str, sources: Optional[list] = None) -> str:
    """
    Wrap raw content in a clean Markdown report template.

    Args:
        topic   : Research topic (used as the H1 heading).
        content : The main body text / summary from the agent.
        sources : Optional list of source URL strings to append.

    Returns:
        A formatted Markdown string.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    md = f"# Research Report: {topic}\n\n"
    md += f"**Generated on:** {timestamp}  \n"
    md += f"**Agent:** Research Agent (Phase 1)  \n\n"
    md += "---\n\n"
    md += "## Summary\n\n"
    md += content.strip()
    md += "\n\n"

    if sources:
        md += "---\n\n"
        md += "## Sources\n\n"
        for i, src in enumerate(sources, start=1):
            md += f"{i}. {src}\n"
        md += "\n"

    md += "---\n"
    md += "*Report generated by AI Research Agent — Phase 1*\n"
    return md


# ─────────────────────────────────────────────────────────────────────────────
# Main public functions — these are what the agent calls
# ─────────────────────────────────────────────────────────────────────────────

def save_report(
    topic: str,
    content: str,
    sources: Optional[list] = None,
    file_format: str = "md",
    custom_filename: Optional[str] = None,
) -> dict:
    """
    Save a research report to the outputs/ folder.

    Args:
        topic           : Research topic (e.g. "LangChain agents").
                          Used in the filename and as the report heading.
        content         : The main report text / summary to save.
        sources         : Optional list of source URLs to include at the bottom.
        file_format     : "md" for Markdown (default) or "txt" for plain text.
        custom_filename : Override the auto-generated filename if needed.

    Returns:
        dict with keys:
            "success"       → True / False
            "filepath"      → absolute path of the saved file (str)
            "filename"      → just the filename (str)
            "message"       → human-readable status message (str)
            "error"         → only present on failure (str)

    Usage (from research_agent.py):
        from tools.file_saver import save_report

        result = save_report(
            topic    = "LangChain agents",
            content  = llm_summary,
            sources  = ["https://...", "https://..."],
        )
        if result["success"]:
            print(f"Saved to: {result['filepath']}")
    """

    # ── Validate inputs ───────────────────────────────────────────────────────
    if not topic or not topic.strip():
        return {"success": False, "filepath": "", "filename": "", "message": "", "error": "Topic cannot be empty."}

    if not content or not content.strip():
        return {"success": False, "filepath": "", "filename": "", "message": "", "error": "Content cannot be empty. Nothing to save."}

    if file_format not in ("md", "txt"):
        return {"success": False, "filepath": "", "filename": "", "message": "", "error": f"Unsupported format '{file_format}'. Use 'md' or 'txt'."}

    # ── Build filename ────────────────────────────────────────────────────────
    if custom_filename:
        # Strip any existing extension, then re-add cleanly
        base_name = Path(custom_filename).stem
        filename  = f"{base_name}.{file_format}"
    else:
        slug      = _slugify(topic)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename  = f"report_{slug}_{timestamp}.{file_format}"

    # ── Prepare directory and full path ──────────────────────────────────────
    try:
        out_dir  = _ensure_outputs_dir()
        filepath = out_dir / filename

        # ── Build file body ───────────────────────────────────────────────────
        if file_format == "md":
            body = _build_markdown(topic, content, sources)
        else:
            # Plain text version — simple and readable
            timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            body  = f"RESEARCH REPORT: {topic.upper()}\n"
            body += f"Generated on   : {timestamp_str}\n"
            body += "=" * 60 + "\n\n"
            body += content.strip() + "\n\n"
            if sources:
                body += "=" * 60 + "\nSOURCES\n" + "=" * 60 + "\n"
                for i, src in enumerate(sources, start=1):
                    body += f"{i}. {src}\n"

        # ── Write to disk ─────────────────────────────────────────────────────
        filepath.write_text(body, encoding="utf-8")

        return {
            "success" : True,
            "filepath": str(filepath),
            "filename": filename,
            "message" : f"Report saved successfully → outputs/{filename}",
        }

    except OSError as os_err:
        return {
            "success" : False,
            "filepath": "",
            "filename": "",
            "message" : "",
            "error"   : f"File system error — {os_err}",
        }

    except Exception as exc:
        return {
            "success" : False,
            "filepath": "",
            "filename": "",
            "message" : "",
            "error"   : f"Unexpected error — {type(exc).__name__}: {exc}",
        }


def list_saved_reports() -> dict:
    """
    List all report files currently in the outputs/ folder.

    Returns:
        dict with keys:
            "reports" → list of filename strings (sorted newest first)
            "count"   → total number of reports
            "dir"     → absolute path of the outputs/ folder
            "error"   → only present if outputs/ can't be read
    """
    try:
        out_dir = _ensure_outputs_dir()
        files   = sorted(
            [f.name for f in out_dir.iterdir() if f.is_file() and f.suffix in (".md", ".txt")],
            reverse=True,   # newest first (filenames have timestamps)
        )
        return {
            "reports": files,
            "count"  : len(files),
            "dir"    : str(out_dir),
        }

    except Exception as exc:
        return {
            "reports": [],
            "count"  : 0,
            "dir"    : str(OUTPUTS_DIR),
            "error"  : f"Could not list reports — {exc}",
        }


def read_report(filename: str) -> dict:
    """
    Read back a saved report from outputs/.

    Args:
        filename : The filename (e.g. "report_langchain_agents_20240501.md")

    Returns:
        dict with keys:
            "success"  → True / False
            "filename" → the filename
            "content"  → file contents as a string
            "error"    → only present on failure
    """
    try:
        out_dir  = _ensure_outputs_dir()
        filepath = out_dir / filename

        if not filepath.exists():
            return {
                "success" : False,
                "filename": filename,
                "content" : "",
                "error"   : f"File not found: outputs/{filename}",
            }

        content = filepath.read_text(encoding="utf-8")
        return {
            "success" : True,
            "filename": filename,
            "content" : content,
        }

    except Exception as exc:
        return {
            "success" : False,
            "filename": filename,
            "content" : "",
            "error"   : f"Could not read file — {exc}",
        }


# ─────────────────────────────────────────────────────────────────────────────
# Quick self-test  →  run:  python tools/file_saver.py
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("file_saver.py — Self Test")
    print("=" * 60)

    # Test 1 — Save a Markdown report
    print("\n[Test 1] Saving a Markdown report...")
    result = save_report(
        topic   = "LangChain Agents Overview",
        content = (
            "LangChain agents are systems that use LLMs to decide which tools "
            "to call and in what order, based on the user's goal. They combine "
            "reasoning (via the LLM) with action (via tools like web search, "
            "calculators, or file I/O).\n\n"
            "Key components:\n"
            "- Agent loop: the LLM thinks, picks a tool, runs it, observes output.\n"
            "- Tools: Python functions the agent can call.\n"
            "- Memory: optional context from past interactions.\n"
            "- LangChain provides ready-made agent types: ReAct, OpenAI Functions, etc."
        ),
        sources = [
            "https://python.langchain.com/docs/modules/agents/",
            "https://blog.langchain.dev/",
        ],
        file_format = "md",
    )

    if result["success"]:
        print(f"PASS — {result['message']}")
    else:
        print(f"FAIL — {result['error']}")

    # Test 2 — Save a plain text report
    print("\n[Test 2] Saving a plain text report...")
    result_txt = save_report(
        topic       = "Groq API Speed Test",
        content     = "Groq's LPU inference engine delivers extremely fast token generation. "
                      "Benchmark: ~500 tokens/sec on LLaMA-3-70B compared to ~30 tokens/sec on typical GPU.",
        file_format = "txt",
    )

    if result_txt["success"]:
        print(f"PASS — {result_txt['message']}")
    else:
        print(f"FAIL — {result_txt['error']}")

    # Test 3 — List saved reports
    print("\n[Test 3] Listing outputs/ folder...")
    listing = list_saved_reports()
    if "error" in listing:
        print(f"FAIL — {listing['error']}")
    else:
        print(f"PASS — Found {listing['count']} report(s) in {listing['dir']}")
        for fname in listing["reports"]:
            print(f"         • {fname}")

    print("\n" + "=" * 60)
    print("All tests complete. file_saver.py is working correctly.")
=======


# ── Main function used by research_agent.py ──────────────────────────────────
def save_report(topic: str, content: str, output_dir: str = "outputs") -> str:
    """
    Save a research report to the outputs/ folder as a markdown file.

    Args:
        topic      (str): The research topic (used to name the file).
        content    (str): The full report content (markdown text).
        output_dir (str): Folder to save in. Default is 'outputs/'.

    Returns:
        str: The full path to the saved file.

    Example:
        path = save_report("LangChain agents", "## Summary\n...")
        print(f"Saved to: {path}")
    """
    # ── Create outputs/ folder if it doesn't exist ───────────────────────────
    os.makedirs(output_dir, exist_ok=True)

    # ── Build a clean filename from the topic ────────────────────────────────
    safe_name = _make_safe_filename(topic)
    filename  = f"report_{safe_name}.md"
    filepath  = os.path.join(output_dir, filename)

    # ── Build the full markdown file content ─────────────────────────────────
    timestamp   = datetime.now().strftime("%Y-%m-%d %H:%M")
    full_content = _build_markdown(topic, content, timestamp)

    # ── Write to file ────────────────────────────────────────────────────────
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(full_content)

    print(f"💾  Report saved → {filepath}")
    return filepath


# ── Bonus: save as plain text ─────────────────────────────────────────────────
def save_report_txt(topic: str, content: str, output_dir: str = "outputs") -> str:
    """
    Save the report as a plain .txt file instead of markdown.
    Useful as a backup format.
    """
    os.makedirs(output_dir, exist_ok=True)

    safe_name = _make_safe_filename(topic)
    filepath  = os.path.join(output_dir, f"report_{safe_name}.txt")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"Research Report: {topic}\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
        f.write("=" * 60 + "\n\n")
        f.write(content)

    print(f"💾  TXT report saved → {filepath}")
    return filepath


# ── List all saved reports ────────────────────────────────────────────────────
def list_reports(output_dir: str = "outputs") -> list[str]:
    """
    Returns a list of all saved report filenames in the outputs/ folder.

    Returns:
        list of str: filenames like ['report_langchain_agents.md', ...]
    """
    if not os.path.exists(output_dir):
        return []

    files = [
        f for f in os.listdir(output_dir)
        if f.startswith("report_") and (f.endswith(".md") or f.endswith(".txt"))
    ]
    return sorted(files)


# ── Helper: make a safe filename ──────────────────────────────────────────────
def _make_safe_filename(topic: str) -> str:
    """
    Converts a topic string into a safe filename.
    Example: "LangChain agents & tools" → "langchain_agents__tools"
    """
    safe = topic.lower()
    safe = re.sub(r"[^\w\s-]", "", safe)     # remove special chars
    safe = re.sub(r"[\s-]+",   "_", safe)    # spaces → underscores
    safe = safe.strip("_")
    return safe[:60]                          # max 60 chars


# ── Helper: build the full markdown report ────────────────────────────────────
def _build_markdown(topic: str, content: str, timestamp: str) -> str:
    """
    Wraps the content in a clean markdown document with a header and footer.
    """
    return f"""# Research Report: {topic}

> **Generated:** {timestamp}  
> **Powered by:** AI Research Agent (Groq + Tavily)

---

{content}

---

*Report generated automatically by AI Research Agent — Phase 1*
"""


# ── Quick test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("Testing file_saver.py...\n")

    # Save a dummy report
    test_path = save_report(
        topic   = "LangChain agents",
        content = "## Overview\n\nLangChain is a framework for building LLM apps.\n\n## Key Points\n- Supports agents\n- Works with many LLMs\n"
    )

    print(f"\n✅ Saved to: {test_path}")
    print(f"\n📂 All saved reports: {list_reports()}")
>>>>>>> a1f9972 (reseacrh_agent connected with the file_saver.py)
